### ISSUE TITLE
Maven deploy/release to OSSRH and Central

### ISSUE THREAD

**Issue by IgorRodchenkov** [sbmlteam/jsbml#131] opened 2016-11-16 22:54 UTC
Please consider deployment of the jsbml maven artifacts to OSSRH instead of m2repo* directories hosted via Sourceforge Project Web... This is easy really. See http://central.sonatype.org/pages/ossrh-guide.html.

**Comment by daemontus** [comment] 2016-11-24 10:43
Or at least make the project compatible with jitpack.io - the 1.2-beta1 actually builds fine there, just the dependencies are kind of messed up (jitpack will change the groupId to avoid collisions, but the dependencies still point to the original groupId, so the resolution fails)

**Comment by niko-rodrigue** [comment] 2016-11-24 10:58
The long term plan was always to deploy to maven central, that's why I created a cleaned repository on sourceforge to avoid all the mess that was on the old EBI repository. That's just that it is a very low priority has we already have a working repo. I am starting right now to register JSBML to OSSRH.

**Comment by daemontus** [comment] 2016-11-24 11:54
Oh, ok, never mind then :)

**Comment by mhucka** [comment] 2016-12-01 05:02
Hate to ask a dumb question, but can someone elaborate about what relationship (if any) there is between jitpack.io and maven, and the reason to target jitpack.io?  (This is an honest question – I've never heard about it until now.)

**Comment by daemontus** [comment] 2016-12-01 09:59
Maven is build automation tool whereas jitpack is a repository, but what you are probably thinking about are Maven repositories, which Maven uses to download plug-ins and dependencies.
There is a lot of big public repositories - Maven Central repository, JCenter, etc.. But most of them require you to have an account and publish the artifacts you want to distribute yourself (or have a script). And then you might also want a snapshot repository where latest builds are accessible.
All things considered, it's a reasonable overhead to pay if your library is a big, well established piece of software. But for smaller projects, it might be a bit tiresome. 
To have a middle ground between publishing to Maven Central and not publishing at all, Jitpack provides a sort of "lazily initialised" Maven repository. It means that you can use any Maven or Gradle repository on Github or Bitbucket as your dependency and as soon as you request that dependency for the first time, Jitpack will clone the repository, build it and save the resulting jars somewhere on their server, so that they are accessible to everyone as a standard dependency.
The nice thing is that you can access any specific commit this way or any of the releases which are created here on github with very little setup on your part :) 

(Oh, and just in case: I am in no way associated with jitpack, it just saved us a lot of time here and there, so I mention it from time to time when people seem reluctant to publish to Maven Central :))

**Comment by niko-rodrigue** [comment] 2016-12-01 10:08
btw, JSBML is available from Maven central I still need to test it properly and update the documentations but it is there.

**Comment by daemontus** [comment] 2016-12-01 10:11
Awesome! Thank you very much for that :)

**Comment by mglont** [comment] 2016-12-01 18:34
this is great, thank you, Nico! The problem is that org.mangosdk:spi:0.2.4 is not in maven central:

Could not find org.mangosdk.spi:spi:0.2.4.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/mangosdk/spi/spi/0.2.4/spi-0.2.4.pom
    https://repo1.maven.org/maven2/org/mangosdk/spi/spi/0.2.4/spi-0.2.4.

Maybe the way to go is to move to http://metainf-services.kohsuke.org/ ?

**Comment by mhucka** [comment] 2016-12-02 01:43
@daemontus Thanks for that detailed explanation.

**Comment by niko-rodrigue** [comment] 2016-12-05 16:46
Why would it be a problem that org.mangosdk:spi:0.2.4 is not in maven central ? It should get downloaded automatically from the EBI repo. We could look at putting it to maven central or switching to something else later but I don't think it is necessary right now and it won't happen before the 1.2 release.

**Comment by matthiaskoenig** [comment] 2016-12-05 17:38
@mglont 
The dependency is available from 
https://mvnrepository.com/artifact/org.mangosdk.spi/spi/0.2.4
Just add the repository to your pom.xml and it should be resolved.

**Comment by mglont** [comment] 2016-12-09 15:12
Thank you, Nico and Matthias, indeed it is possible to ask all projects using jsbml to add the repository Matthias indicated to their pom file so that spi can be retrieved.

But stepping back a bit, spi is only used to preprocess JSBML classes, so maybe it should not be a transitive dependency. If we add mark the artifact as optional[1] in the jsbml pom, then Maven shouldn't try to include it in the JSBML clients' dependency tree.

[1] https://maven.apache.org/pom.html#POM_Relationships

**Comment by niko-rodrigue** [comment] 2016-12-09 15:27
Indeed, I can mark it as optional for sure. 

But I still wonder why it does not find it automatically when the repository needed is defined in the jsbml-core pom file !

**Comment by mglont** [comment] 2016-12-09 15:32
I think it's because my pom file does not extend jsbml-core.

**Comment by niko-rodrigue** [comment] 2016-12-09 15:43
I have added the jar as optional. I will close this issue as resolved and if you still have issues, let's open a new issue.

**Closed by niko-rodrigue** 2016-12-09 15:43 UTC
Labels: enhancement, feature-request, jsbml 1.2, maven

**Comment by IgorRodchenkov** [comment] 2016-12-09 19:58
Why did you decided to use different groupId for jsbml maven modules (see: http://search.maven.org/#search%7Cga%7C1%7Cjsbml)? And also why 'org.sbml.jsbml' and not just 'org.sbml'? Epecially, when all those get released at the same time and have same latest version...

**Comment by niko-rodrigue** [comment] 2016-12-12 15:15
We used different grouIds because we could and we like the separation like that. 'ext' are extensions to the SBML language, they are all developed by us but could be developed and deployed separately. Same for modules, which are utilities added on top of jsbml.
Just 'org.sbml' would correspond to anything that is developed under the umbrella of http://sbml.org. Libsbml or the online validator, for example, if they deploy some artefacts, they could use grouId starting with org.sbml.libsbml or org.sbml.validator*.

**Comment by IgorRodchenkov** [comment] 2016-12-12 15:35
If you believe that, fine with me, but I am not sure it helps... Might I am
wrong; anyway, this is a minor thing.
