### ISSUE TITLE
EmptyStackException

### ISSUE THREAD

**Issue by piotr-gawron** [sbmlteam/jsbml#159] opened 2018-12-31 13:18 UTC
When parsing one example from multi package specification (http://co.mbine.org/specifications/sbml.level-3.version-1.multi.version-1.release-1.pdf) I got `java.util.EmptyStackException`
```
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:802)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:542)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromStream(SBMLReader.java:552)
	at org.sbml.jsbml.SBMLReader.readSBMLFromStream(SBMLReader.java:251)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:128)
```

I narrowed down the problem to a small SBML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version1/core"
	level="3" version="1"
	xmlns:multi="http://www.sbml.org/sbml/level3/version1/multi/version1"
	multi:required="true">
	<model name="bionetgen_example_egfr_simple">
		<multi:listOfSpeciesTypes>
			<multi:bindingSiteSpeciesType
				multi:id="st_EGF_bs_R" />
			<multi:speciesType multi:id="st_EGF">
				<multi:listOfSpeciesTypeInstances>
					<multi:component multi:id="R"
						multi:speciesType="st_EGF_bs_R" />
				</multi:listOfSpeciesTypeInstances>
			</multi:speciesType>
		</multi:listOfSpeciesTypes>
	</model>
</sbml>
```

The whole file obtained from the specification is in the attachment ([bionetgen.xml.zip](https://github.com/sbmlteam/jsbml/files/2718378/bionetgen.xml.zip)).

**Comment by niko-rodrigue** [comment] 2019-01-03 15:01
Thanks for the report, I will have a look at it.

**Comment by niko-rodrigue** [comment] 2019-01-04 19:04
The problem is the "component" element. It is an error, may be the example was generated with on old version of libsbml or other software. If you look at the first example, the listOfSpeciesTypeInstances contain only some "speciesTypeInstance" element. You can check as well the specs, figure 3 at the beginning of section 3.8. 

I will try to make jsbml report this properly instead of throwing an exception.

**Comment by niko-rodrigue** [comment] 2019-01-11 14:43
This should be fixed now.

**Closed by niko-rodrigue** 2019-01-11 14:43 UTC
Labels: LibSBML compatibility

**Comment by piotr-gawron** [comment] 2019-01-14 13:31
@niko-rodrigue 
No I didn't report it there. For me the specification was really hard to digest and gave up at some point. But I assumed it's correct...

**Comment by niko-rodrigue** [comment] 2019-01-14 13:56
I will open a tracker item for them so that they can fix this.

**Comment by piotr-gawron** [comment] 2019-01-14 15:50
Can you share it with me? Privately or put it here

**Comment by niko-rodrigue** [comment] 2019-01-14 19:52
Here is the link: https://sourceforge.net/p/sbml/sbml-specifications/359/. Just realized that I forgot to mention you..
